kind: Job
apiVersion: batch/v1
metadata:
  name: jobname
spec:
  template:
    spec:
      hostIPC: true
      containers:
      - name: icenetcontainer
        image: "halyjo/icenetimage:latest"
        workingDir: /storage/experiments/icenet/
        command: ["/bin/bash", "-c"]
        args: ["source activate icenet && <your entrypoint>"]
        stdin: true
        tty: true
        env: 
        - name: "WANDB_API_KEY"
          value: <Your wandb api key>
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0